import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApi} from '../server/app.mjs';
test('owner panel: deny GM/anonymous, preserve revisions, restore, ban, audit, survive restart',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'nyxia-owner-')),database=join(dir,'test.sqlite');
 let app=createApi({database,origin:'http://test.local',secure:false});
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
 let url=`http://127.0.0.1:${app.server.address().port}`;
 async function call(path,body,cookie,origin='http://test.local',method=body?'POST':'GET'){
  const r=await fetch(url+'/api/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
  return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};
 }
 try{
  const a=await call('register',{name:'owner',password:'test-long-password-123'}), b=await call('register',{name:'friend',password:'test-long-password-123'});
  assert.equal((await call('admin/overview')).status,401);
  assert.equal((await call('admin/overview',null,a.cookie)).status,403);
  const db=new DatabaseSync(database);db.prepare('INSERT INTO panel_owner VALUES(1,1)').run();db.close();
  const data={characters:[{id:'hero',name:'Tester',isGM:true,level:5,gold:500,inventory:[{id:'weapon-1',upgradeLevel:8}],quests:{test:true}},null,null],bank:[],diamonds:100};
  assert.equal((await call('backup',{revision:0,data},b.cookie,undefined,'PUT')).status,200);
  for(const path of ['overview','accounts','account?id=2','chat','clans','market','duels','audit']){
   assert.equal((await call('admin/'+path,null,b.cookie)).status,403);
   const r=await call('admin/'+path,null,a.cookie);assert.equal(r.status,200,path);
   assert.ok(!JSON.stringify(r.data).includes('"password"'));
  }
  const edited=structuredClone(data);edited.diamonds=250;
  assert.equal((await call('admin/account/save',{id:2,revision:1,data:edited,reason:'test adjustment'},b.cookie)).status,403);
  assert.equal((await call('admin/account/save',{id:2,revision:1,data:edited,reason:'test adjustment'},a.cookie,'http://evil.local')).status,403);
  assert.equal((await call('admin/account/save',{id:2,revision:1,data:edited,reason:'test adjustment'},a.cookie)).status,200);
  assert.equal((await call('backup',{revision:1,data},b.cookie,undefined,'PUT')).status,409);
  let detail=(await call('admin/account?id=2',null,a.cookie)).data;
  assert.deepEqual(detail.data.characters,data.characters);assert.equal(detail.snapshots.length,1);
  assert.equal((await call('admin/account/save',{id:2,revision:2,data:{...edited,characters:[null,null,null]},reason:'bad deletion'},a.cookie)).status,400);
  assert.equal((await call('admin/account/restore',{id:2,revision:2,snapshot:detail.snapshots[0].id,reason:'undo test'},a.cookie)).status,200);
  assert.deepEqual((await call('backup',null,b.cookie)).data.data,{...data,diamonds:0});
  assert.equal((await call('admin/account/block',{id:1,blocked:true,reason:'lock owner'},a.cookie)).status,400);
  assert.equal((await call('admin/account/block',{id:2,blocked:true,reason:'test ban'},a.cookie)).status,200);
  assert.equal((await call('backup',null,b.cookie)).status,401);
  assert.equal((await call('login',{name:'friend',password:'test-long-password-123'})).status,403);
  assert.equal((await call('admin/account/block',{id:2,blocked:false,reason:'test unban'},a.cookie)).status,200);
  assert.equal((await call('login',{name:'friend',password:'test-long-password-123'})).status,200);
  assert.equal((await call('admin/audit',null,a.cookie)).data.length,4);
  const rules=(await call('admin/drops',null,a.cookie)).data;
  assert.equal((await call('admin/drops',null,b.cookie)).status,401);
  const c=(await call('login',{name:'friend',password:'test-long-password-123'})).cookie;
  assert.equal((await call('admin/drops',null,c)).status,403);
  const changed=structuredClone(rules.data);changed.chestTables={'1':[{key:rules.catalog[0].key,weight:1,level:7}]};
  assert.equal((await call('admin/drops/save',{revision:0,data:changed,reason:'test rules'},c)).status,403);
  assert.equal((await call('admin/drops/save',{revision:0,data:changed,reason:'test rules'},a.cookie)).status,200);
  assert.equal((await call('drop-settings',null,c)).data.data.chestTables['1'][0].level,7);
  assert.equal((await call('admin/drops/save',{revision:0,data:changed,reason:'stale rules'},a.cookie)).status,409);
  assert.equal((await call('admin/drops/save',{revision:1,data:{...changed,chests:{weaponPct:0.8,armorPct:0.8}},reason:'bad rules'},a.cookie)).status,400);
  assert.equal((await call('admin/drops/save',{revision:1,data:{...changed,chestTables:{'1':[{key:'not-real',weight:1,level:1}]}},reason:'bad item'},a.cookie)).status,400);
  assert.equal((await call('admin/drops/restore',{revision:1,snapshot:0,reason:'undo rules'},a.cookie)).status,200);
  assert.equal((await call('drop-settings',null,c)).data.data.chestTables,undefined);
  const socialDb=new DatabaseSync(database);socialDb.prepare('INSERT INTO friendships VALUES(1,2,?)').run(Date.now());
  assert.equal((await call('admin/account/mute',{id:2,muted:true,hours:1,reason:'spam test'},a.cookie)).status,200);
  assert.equal((await call('chat/messages',{author:'friend',text:'hello'},c)).status,403);
  assert.equal((await call('social/messages/1',{text:'hello'},c)).status,403);
  assert.equal((await call('backup',null,c)).status,200);
  socialDb.prepare('UPDATE account_mutes SET expires_at=? WHERE account=2').run(Date.now()-1);
  assert.equal((await call('chat/messages',{author:'friend',text:'hello'},c)).status,200);
  assert.equal((await call('social/messages/1',{text:'hello'},c)).status,200);
  assert.equal((await call('admin/account/block',{id:2,blocked:true,hours:-1,reason:'bad duration'},a.cookie)).status,400);
  assert.equal((await call('admin/account/block',{id:2,blocked:true,hours:1,reason:'one hour ban'},a.cookie)).status,200);
  assert.equal((await call('login',{name:'friend',password:'test-long-password-123'})).status,403);
  socialDb.prepare('UPDATE account_blocks SET expires_at=? WHERE account=2').run(Date.now()-1);
  assert.equal((await call('login',{name:'friend',password:'test-long-password-123'})).status,200);
  const character=(await call('admin/account?id=2',null,a.cookie)).data;
  character.data.race='elmorad';character.data.characters[0].race='elmorad';character.data.characters[0].nickname='YeniAd';
  assert.equal((await call('admin/account/save',{id:2,revision:character.revision,data:character.data,reason:'rename and race'},a.cookie)).status,200);
  assert.equal((await call('admin/account?id=2',null,a.cookie)).data.data.characters[0].inventory[0].upgradeLevel,8);
  socialDb.close();
  await app.close(); app=createApi({database,origin:'http://test.local',secure:false});
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r)); url=`http://127.0.0.1:${app.server.address().port}`;
  assert.equal((await call('admin/overview',null,a.cookie)).status,200);
  assert.equal((await call('admin/account?id=2',null,a.cookie)).data.snapshots.length,3);
 }finally{await app.close();rmSync(dir,{recursive:true});}
});
