import React,{useState} from 'react';
const labels={guaranteedChests:'Garantili sandık adedi (0–10)',guaranteedChestTier:'Garantili sandık tier (1–6)',goldMin:'En az altın',goldMax:'En çok altın',xp:'EXP',dropChance:'Eşya düşme %',chestChance:'Sandık düşme %',bonusGoldMin:'En az bonus altın',bonusGoldMax:'En çok bonus altın',equipDropChance:'Eşya %',chestDropChance:'Sandık %',scrollDropChance:'Parşömen %',powerMult:'Güç çarpanı',goldMult:'Altın çarpanı',dropMult:'Drop çarpanı',weaponPct:'Silah %',armorPct:'Zırh %',specialUniqueChance:'Özel sandık eşsiz silah %',specialAccessoryChance:'Özel sandık T6 takı %'};
function Fields({value,change}){return <div className="fields">{Object.entries(value).filter(([k,v])=>typeof v==='number').map(([k,v])=>{const pct=/Chance$|Pct$/.test(k);return <label key={k}>{labels[k]||k}<input type="number" min="0" max={pct?100:undefined} step={pct||/Mult$/.test(k)?'0.01':'1'} value={pct?Math.round(v*10000)/100:v} onChange={e=>change({...value,[k]:Number(e.target.value)/(pct?100:1)})}/></label>;})}</div>}
function Pool({value,catalog,onChange}){
 const [search,setSearch]=useState(''),[key,setKey]=useState('');const list=catalog.filter(x=>(x.name+' '+x.class+' '+x.kind).toLowerCase().includes(search.toLowerCase()));
 const total=(value||[]).reduce((n,x)=>n+x.weight,0);
 return <div className="loot-pool"><p className="muted">{value?.length?'Özel havuz etkin: eşya düşerse bu listeden bir eşya seçilir.':'Varsayılan oyun havuzu kullanılıyor.'} Ağırlıklar birbirine oranlanır; canavarın eşya düşürme yüzdesi ayrıca uygulanır.</p>
 <div className="toolbar"><input aria-label="Eşya kataloğunda ara" placeholder="Eşya ara…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Eşya seç" value={key} onChange={e=>setKey(e.target.value)}><option value="">Katalogdan eşya seç</option>{list.map(x=><option key={x.key} value={x.key}>{x.name} · T{x.tier} · {x.class||x.slot}</option>)}</select><button type="button" disabled={!key} onClick={()=>{onChange([...(value||[]),{key,weight:1,level:1}]);setKey('');}}>Ekle</button></div>
 {(value||[]).map((r,i)=>{const item=catalog.find(x=>x.key===r.key);return <div className="pool-row" key={i}><strong>{item?.name||r.key}<small>{item?.class} · T{item?.tier} · %{total?(r.weight/total*100).toFixed(2):0}</small></strong><label>+Seviye<input type="number" min="1" max={item?.maxLevel||8} value={r.level} onChange={e=>onChange(value.map((x,n)=>n===i?{...x,level:Number(e.target.value)}:x))}/></label><label>Ağırlık<input type="number" min="0.01" step="0.01" value={r.weight} onChange={e=>onChange(value.map((x,n)=>n===i?{...x,weight:Number(e.target.value)}:x))}/></label><button type="button" onClick={()=>{const rest=value.filter((_,n)=>n!==i);onChange(rest.length?rest:null);}}>Kaldır</button></div>})}
 {value?.length>0&&<button type="button" onClick={()=>onChange(null)}>Varsayılan havuza dön</button>}</div>;
}
export default function DropEditor({payload,busy,save}){
 const [data,setData]=useState(()=>structuredClone(payload.data)),[reason,setReason]=useState(''),[section,setSection]=useState('monsters'),[mapId,setMapId]=useState(payload.maps[0]?.id),[chest,setChest]=useState('1');
 const change=(fn)=>setData(d=>{const n=structuredClone(d);fn(n);return n;});
 const map=payload.maps.find(m=>m.id===mapId);
 return <><section className="card"><h3>Canlı ödül ayarları · v{payload.revision}</h3><p>Kaydettiğin kurallar tüm oyunculara en geç 30 saniyelik yenilemede ulaşır. Mevcut eşyalar değişmez. Her sandık açılışı özel havuzdan bir eşya seçer.</p><div className="toolbar">{[['monsters','Canavarlar'],['chests','Sandıklar'],['bosses','Savaş Alanı']].map(([id,label])=><button key={id} className={section===id?'primary':''} onClick={()=>setSection(id)}>{label}</button>)}</div></section>
 {section==='monsters'&&<><label>Harita<select value={mapId} onChange={e=>setMapId(e.target.value)}>{payload.maps.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label>{map?.monsters.map(m=><details className="card" key={m.id}><summary>{m.name}</summary><Fields value={data.maps[mapId].monsters[m.id]} change={v=>change(d=>{d.maps[mapId].monsters[m.id]=v;})}/><Pool catalog={payload.catalog} value={data.maps[mapId].monsters[m.id].loot} onChange={v=>change(d=>{d.maps[mapId].monsters[m.id].loot=v;})}/></details>)}</>}
 {section==='chests'&&<><section className="card"><h3>Varsayılan dağılım</h3><Fields value={data.chests} change={v=>change(d=>{d.chests=v;})}/><p>Kalan %{(100*(1-data.chests.weaponPct-data.chests.armorPct)).toFixed(2)} takıdır. Silah ve zırh yüzdeleri toplamı 100'ü geçemez.</p></section><section className="card"><label>İçeriği düzenlenecek sandık<select value={chest} onChange={e=>setChest(e.target.value)}>{['1','2','3','4','5','6','special'].map(x=><option key={x} value={x}>{x==='special'?'Özel etkinlik sandığı':`Tier ${x} sandık`}</option>)}</select></label><Pool catalog={payload.catalog} value={data.chestTables?.[chest]} onChange={v=>change(d=>{d.chestTables||={};d.chestTables[chest]=v;})}/></section></>}
 {section==='bosses'&&<><section className="card"><h3>Canavar ara çarpanları</h3><Fields value={data.warzoneHunt} change={v=>change(d=>{d.warzoneHunt=v;})}/></section>{payload.bosses.map(b=><section className="card" key={b.id}><h3>{b.name}</h3><Fields value={data.warzoneBosses[b.id]} change={v=>change(d=>{d.warzoneBosses[b.id]=v;})}/><Pool catalog={payload.catalog} value={data.warzoneBosses[b.id].loot} onChange={v=>change(d=>{d.warzoneBosses[b.id].loot=v;})}/></section>)}</>}
 <section className="card"><label>Yayınlama açıklaması<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Örn. T2 sandık havuzu düzenlendi"/></label><div className="toolbar"><button className="primary" disabled={busy||reason.trim().length<3} onClick={()=>{if(confirm('Bu drop ve sandık kuralları tüm oyunculara yayınlansın mı?'))save('drops/save',{data,revision:payload.revision,reason});}}>Kuralları yayınla</button></div><details><summary>Önceki kurala geri dön</summary>{payload.history?.map(h=><div key={h.revision} className="toolbar"><span>v{h.revision} · {new Date(h.created_at).toLocaleString('tr-TR')}</span><button disabled={busy||reason.trim().length<3} onClick={()=>{if(confirm('Önceki kurallar tüm oyunculara yayınlansın mı?'))save('drops/restore',{revision:payload.revision,snapshot:h.revision,reason});}}>Geri yükle</button></div>)}</details></section></>;
}
