import React,{useState} from 'react';
import {ask} from './dialog';
import VisualLootPool from './VisualLootPool';
import {defaultLootPool} from './lootPoolPreview';
import MonsterPortrait from '../components/MonsterPortrait';
import {Package} from '../components/icons/GameIcons';
const labels={guaranteedChests:'Garantili sandık adedi (0–10)',guaranteedChestTier:'Garantili sandık tier (1–6)',goldMin:'En az altın',goldMax:'En çok altın',xp:'EXP',dropChance:'Eşya düşme %',chestChance:'Sandık düşme %',bonusGoldMin:'En az bonus altın',bonusGoldMax:'En çok bonus altın',equipDropChance:'Eşya %',chestDropChance:'Sandık %',scrollDropChance:'Parşömen %',powerMult:'Güç çarpanı',goldMult:'Altın çarpanı',dropMult:'Drop çarpanı',weaponPct:'Silah %',armorPct:'Zırh %',specialUniqueChance:'Özel sandık eşsiz silah %',specialAccessoryChance:'Özel sandık T6 takı %'};
function Fields({value,change}){return <div className="fields">{Object.entries(value).filter(([k,v])=>typeof v==='number').map(([k,v])=>{const pct=/Chance$|Pct$/.test(k);return <label key={k}>{labels[k]||k}<input type="number" min="0" max={pct?100:undefined} step={pct||/Mult$/.test(k)?'0.01':'1'} value={pct?Math.round(v*10000)/100:v} onChange={e=>change({...value,[k]:Number(e.target.value)/(pct?100:1)})}/></label>;})}</div>}

export default function DropEditor({payload,busy,save}){
 const [data,setData]=useState(()=>structuredClone(payload.data)),[reason,setReason]=useState(''),[section,setSection]=useState('monsters'),[mapId,setMapId]=useState(payload.maps[0]?.id),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[clipboard,setClipboard]=useState(null),[specialClass,setSpecialClass]=useState('warrior');
 const change=fn=>setData(d=>{const n=structuredClone(d);fn(n);return n;});
 const map=payload.maps.find(m=>m.id===mapId);
 const targets=section==='monsters'?map.monsters:section==='bosses'?payload.bosses:['1','2','3','4','5','6','special'].map(id=>({id,name:id==='special'?'Özel etkinlik sandığı':`Tier ${id} sandık`,tier:Number(id)||5}));
 const visible=targets.filter(x=>x.name.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))),target=visible.find(x=>x.id===selected)||visible[0];
 const isChest=section==='chests',tier=section==='monsters'?map.tier:target?.tier;
 const config=target?(section==='monsters'?data.maps[mapId].monsters[target.id]:section==='bosses'?data.warzoneBosses[target.id]:{}):{};
 const value=target?(isChest?data.chestTables?.[target.id]:config.loot):null;
 const defaults=target?defaultLootPool(payload.catalog,tier,data,section==='monsters'?{mapTier:tier}:target.id==='special'?{specialClass}:{}).map(r=>({...r,weight:r.weight*100})):[];
 const updateConfig=v=>change(d=>{if(section==='monsters')d.maps[mapId].monsters[target.id]=v;else d.warzoneBosses[target.id]=v;});
 const updatePool=v=>isChest?change(d=>{d.chestTables||={};d.chestTables[target.id]=v;}):updateConfig({...config,loot:v});
 const dirty=JSON.stringify(data)!==JSON.stringify(payload.data);
 return <><section className="card"><h3>Drop atölyesi · v{payload.revision}</h3><p>Canavarı veya sandığı seç, eşya kutusuna dokunarak seviyesini ve oranını düzenle. Değişiklikler yalnızca yayınladığında oyunculara ulaşır.</p><div className="toolbar">{[['monsters','Canavarlar'],['chests','Sandıklar'],['bosses','Savaş Alanı']].map(([id,label])=><button key={id} className={section===id?'primary':''} onClick={()=>{setSection(id);setSelected('');setSearch('');}}>{label}</button>)}</div></section>
 <div className="drop-workbench"><aside className="card drop-targets">{section==='monsters'&&<label>Harita<select value={mapId} onChange={e=>{setMapId(e.target.value);setSelected('');setSearch('');}}>{payload.maps.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label>}<input aria-label="Hedef ara" placeholder="Canavar / sandık ara…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="target-list">{visible.map(m=><button key={m.id} className={target?.id===m.id?'selected':''} onClick={()=>setSelected(m.id)}>{isChest?<Package size={25}/>:<MonsterPortrait monster={m}/>}<span>{m.name}</span></button>)}</div></aside>
 <section className="card">{target?<><header className="drop-target-title">{isChest?<Package size={40}/>:<MonsterPortrait monster={target}/>}<div><h3>{target.name}</h3><small>Tier {tier} · {isChest?'Sandık içeriği':'Ödül tablosu'}</small></div></header>{!isChest&&<Fields value={config} change={updateConfig}/>}{target.id==='special'&&<label>Varsayılan havuzun sınıfı<select value={specialClass} onChange={e=>setSpecialClass(e.target.value)}>{['warrior','rogue','mage'].map(c=><option key={c}>{c}</option>)}</select><small>Varsayılan eşsiz silah sınıfa bağlıdır. Özel havuz yayınlarsan tüm sınıflara aynı liste uygulanır.</small></label>}
 <VisualLootPool key={section+target.id} value={value} defaults={defaults} catalog={payload.catalog} onChange={updatePool} chest={isChest} baseChance={config.dropChance??config.equipDropChance??1} clipboard={clipboard} onCopy={setClipboard}/></>:<p>Aramayla eşleşen hedef yok.</p>}</section></div>
 {isChest&&<details className="card"><summary>Varsayılan sandık dağılımı</summary><Fields value={data.chests} change={v=>change(d=>{d.chests=v;})}/><p>Özel havuzu olmayan sandıklara uygulanır. Silah ve zırh toplamı %100'ü geçemez.</p></details>}
 {section==='bosses'&&<details className="card"><summary>Canavar ara çarpanları</summary><Fields value={data.warzoneHunt} change={v=>change(d=>{d.warzoneHunt=v;})}/></details>}
 <section className="card drop-publish"><label>Yayınlama açıklaması<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Örn. T2 sandık havuzu düzenlendi"/></label><div className="toolbar"><span>{dirty?'Yayınlanmamış değişiklikler var':'Kurallar güncel'}</span><button className="primary" disabled={busy||!dirty||reason.trim().length<3} onClick={async()=>{if(await ask({title:'Bu drop ve sandık kuralları tüm oyunculara yayınlansın mı?'}))save('drops/save',{data,revision:payload.revision,reason});}}>Kuralları yayınla</button></div></section>
 <details className="card"><summary>Önceki kurala geri dön</summary>{payload.history?.map(h=><div key={h.revision} className="toolbar"><span>v{h.revision} · {new Date(h.created_at).toLocaleString('tr-TR')}</span><button disabled={busy||reason.trim().length<3} onClick={async()=>{if(await ask({title:'Önceki kurallar tüm oyunculara yayınlansın mı?'}))save('drops/restore',{revision:payload.revision,snapshot:h.revision,reason});}}>Geri yükle</button></div>)}</details></>;
}
