import React,{useMemo,useState,useEffect,useRef} from 'react';
import {Search,Plus,Trash2,Copy,ClipboardPaste,RotateCcw,Package} from 'lucide-react';
import ItemIcon from '../components/ItemIcon';
import {rollConfiguredLoot} from '../utils/loot';
import './VisualLootPool.css';
function PercentEditor({value,onChange,disabled}){
 const [draft,setDraft]=useState(value.toFixed(2));useEffect(()=>setDraft(value.toFixed(2)),[value]);
 return <label>Havuz oranı %<input aria-label="Havuz oranı yüzde" type="number" min="0.01" max="99.99" step="0.1" disabled={disabled} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{const n=Number(draft);if(Number.isFinite(n)&&n>0&&n<100)onChange(n);else setDraft(value.toFixed(2));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
const kinds={weapon:'Silah',shield:'Kalkan',armor:'Zırh',accessory:'Takı'};
function ItemArt({entry}){const item=useMemo(()=>rollConfiguredLoot([{...entry,weight:1}]),[entry.key,entry.level]);return item?<ItemIcon item={item} size={52}/>:<Package size={32}/>;}
export default function VisualLootPool({value,catalog,onChange,defaults=[],chest=false,baseChance=1,clipboard,onCopy}){
 const [search,setSearch]=useState(''),[tier,setTier]=useState(''),[kind,setKind]=useState(''),[cls,setCls]=useState(''),[selected,setSelected]=useState(null),[catalogOpen,setCatalogOpen]=useState(false);
 const inspectorRef=useRef(null);
 useEffect(()=>{if(selected)inspectorRef.current?.scrollIntoView({block:'nearest',behavior:'auto'});},[selected]);
 const auto=!Array.isArray(value),rows=auto?defaults:value,total=rows.reduce((n,r)=>n+r.weight,0);
 const byKey=useMemo(()=>new Map(catalog.map(x=>[x.key,x])),[catalog]);
 const list=catalog.filter(x=>(!tier||x.tier===Number(tier))&&(!kind||x.kind===kind)&&(!cls||x.class===cls||cls==='common'&&!x.class)&&(x.name||'').toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
 const visibleRows=rows.filter(r=>list.some(i=>i.key===r.key));
 const edit=(next)=>{onChange(next);};
 const index=selected===null?-1:rows.findIndex(r=>r.key+':'+r.level===selected),current=rows[index],info=current&&byKey.get(current.key);
 const changeRow=(patch)=>{const next=rows.map((r,i)=>i===index?{...r,...patch}:r);if(patch.level!==undefined)setSelected(current.key+':'+patch.level);edit(next);};
 const setPercent=percent=>{const rest=total-current.weight;if(rest<=0)return;edit(rows.map((r,i)=>({...r,weight:i===index?percent:r.weight/rest*(100-percent)})));};
 const remove=()=>{edit(rows.filter((_,i)=>i!==index));setSelected(null);};
 return <section className="visual-loot"><div className="loot-status"><span className={auto?'default':'custom'}>{auto?'VARSAYILAN HAVUZ':'ÖZEL HAVUZ'}</span><strong>{rows.length} eşya</strong><small>{chest?'Her açılışta 1 eşya':'Eşya düşerse listeden 1 eşya'}</small></div>
 <div className="loot-tools"><button type="button" onClick={()=>setCatalogOpen(!catalogOpen)}><Plus size={15}/>Eşya ekle</button><button type="button" disabled={!rows.length} onClick={()=>onCopy(structuredClone(rows))}><Copy size={15}/>Kopyala</button><button type="button" disabled={!clipboard} onClick={()=>{if(confirm('Bu hedefin eşya havuzu kopyaladığın listeyle değiştirilsin mi?')){edit(structuredClone(clipboard));setSelected(null);}}}><ClipboardPaste size={15}/>Yapıştır</button><button type="button" onClick={()=>{if(confirm('Bu hedefin özel listesini kaldırıp varsayılan droplara dönülsün mü?')){onChange(null);setSelected(null);}}}><RotateCcw size={15}/>Varsayılan</button></div>
 <p className="loot-explain">{auto?'Kutuyu seçip yukarıdaki yüzde alanına istediğin oranı yaz. Oyunda çıkabilen eşyalar gösteriliyor. Bir eşyayı düzenleyince mevcut oranlar korunarak özel havuz oluşturulur.':'Yüzdeler eşya düşmesi koşuluna bağlıdır; ağırlık değişince otomatik hesaplanır.'} {chest?'Sandık boş listeyle yayınlanamaz.':'Boş özel liste eşya dropunu kapatır; altın ve sandık ödülleri ayrı kalır.'}</p>
<div className="loot-filters"><input aria-label="Eşya kataloğunda ara" value={search} onChange={e=>setSearch(e.target.value)} placeholder="İsimle ara…"/><select aria-label="Tier filtresi" value={tier} onChange={e=>setTier(e.target.value)}><option value="">Tüm tierlar</option>{[1,2,3,4,5,6].map(t=><option key={t} value={t}>Tier {t}</option>)}</select><select aria-label="Tür filtresi" value={kind} onChange={e=>setKind(e.target.value)}><option value="">Tüm türler</option>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="Sınıf filtresi" value={cls} onChange={e=>setCls(e.target.value)}><option value="">Tüm sınıflar</option>{['warrior','rogue','mage','common'].map(c=><option key={c} value={c}>{c==='common'?'Ortak':c}</option>)}</select></div> {current&&info&&<div className="loot-inspector" ref={inspectorRef}><ItemArt entry={current}/><div><h4>{info.name}</h4><small>{kinds[info.kind]} · T{info.tier} · {info.class||'Ortak'}</small><p>Havuz içi: %{(current.weight/(total||1)*100).toFixed(3)}{!chest&&` · Temel öldürme başına: %${(current.weight/(total||1)*baseChance*100).toFixed(3)}`}</p></div><label>+Seviye<input type="number" min={info.minLevel??1} max={info.maxLevel??8} value={current.level} onChange={e=>changeRow({level:Number(e.target.value)})}/></label><PercentEditor value={current.weight/(total||1)*100} onChange={setPercent} disabled={rows.length<2}/><small>Oranı yazıp Enter’a bas. Diğer eşyalar kendi aralarında orantılı ayarlanır. %0 için listeden çıkar.</small><button className="danger" type="button" onClick={remove}><Trash2 size={15}/>Listeden çıkar</button></div>}
 <div className="loot-tile-grid" aria-label="Drop eşyaları">{visibleRows.map((r,i)=>{const item=byKey.get(r.key),id=r.key+':'+r.level;return <button type="button" className={`loot-tile ${id===selected?'selected':''}`} key={id+':'+i} onClick={()=>setSelected(id)} title={`${item?.name} +${r.level}`} aria-label={`${item?.name} +${r.level} düzenle`}><span className="tile-tier">T{item?.tier}</span><ItemArt entry={r}/><span className="tile-name">{item?.name}</span><span className="tile-plus">+{r.level}</span><small>%{total?(r.weight/total*100).toFixed(2):0}</small></button>;})}</div>
 {!!rows.length&&!visibleRows.length&&<p>Filtreye uygun eşya yok. <button type="button" onClick={()=>{setSearch('');setTier('');setKind('');setCls('');}}>Filtreleri temizle</button></p>}
 {!rows.length&&<div className="loot-empty"><Package/><strong>{chest?'Sandığa en az bir eşya ekle':'Bu canavar eşya düşürmeyecek'}</strong><span>Eşya ekle düğmesiyle katalogdan seçebilirsin.</span></div>}
 {catalogOpen&&<div className="loot-catalog"><h4><Search size={17}/>Eşya kataloğu <small>{list.length} sonuç</small></h4><div className="loot-tile-grid catalog-results">{list.map(item=>{const level=item.minLevel??1,entry={key:item.key,level,weight:1},exists=rows.some(r=>r.key===item.key&&r.level===level);return <button type="button" className="loot-tile" key={item.key} disabled={exists} onClick={()=>{edit([...rows,entry]);setSelected(item.key+':'+level);}} aria-label={`${item.name} ekle`}><span className="tile-tier">T{item.tier}</span><ItemArt entry={entry}/><span className="tile-name">{item.name}</span><small>{exists?'Listede':'+ Ekle'}</small></button>;})}</div></div>}
 </section>;
}
