import {useEffect,useState} from 'react';
import {fetchClanVault,updateClanPermissions} from '../services/clanService';
import {CLAN_PERMISSIONS,clanAllowed} from '../data/clanPermissions';
import ItemIcon from './ItemIcon';
import {displayItemName} from '../utils/player';
import {useTranslation} from '../i18n/LanguageContext';
import './ClanManagement.css';
const LABELS={deposit:['Depoya eşya koyma','Deposit items'],withdraw:['Depodan eşya alma','Withdraw items'],invite:['Oyuncu davet etme','Invite players'],kick:['Üye çıkarma','Remove members'],upgrade:['Bina geliştirme','Upgrade buildings'],donate:['Hazineye bağış','Donate to treasury'],dungeon:['Zindana girme','Enter dungeon']};
export default function ClanManagement({player,act,onRefresh}){
 const {lang}=useTranslation(),en=lang==='en';const [data,setData]=useState(null),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('vault');
 const load=async()=>{try{const d=await fetchClanVault();setData(d);setDraft(d.permissions);}catch{setError(en?'Cannot load clan storage.':'Klan deposu yüklenemedi.');}};
 useEffect(()=>{let live=true;fetchClanVault().then(d=>{if(live){setData(d);setDraft(d.permissions);}}).catch(()=>{if(live)setError(en?'Cannot load clan storage.':'Klan deposu yüklenemedi.');});return()=>{live=false};},[player.clan.id]);
 const run=async(type,payload)=>{if(busy)return;setBusy(true);setError('');try{const r=await act(type,payload);if(!r.ok){const messages={clanPermissionDenied:['Bu işlem için yetkin yok.','Permission denied.'],clanVaultFull:['Klan deposu dolu.','Clan storage is full.'],clanBagFull:['Çantanda yer veya taşıma kapasitesi yok.','Your bag is full or overweight.'],clanItemBound:['Bu eşya klan deposuna konamaz.','This item cannot be shared.'],itemNotFound:['Eşya başka bir üye tarafından alınmış olabilir.','Item may already have been taken.']};setError((messages[r.reason]||['İşlem tamamlanamadı.','Operation failed.'])[en?1:0]);}await load();}catch{setError(en?'Connection failed. Try again.':'Bağlantı sorunu. Tekrar dene.');}finally{setBusy(false);}};
 const save=async()=>{setBusy(true);setError('');try{await updateClanPermissions(draft);await load();await onRefresh();}catch{setError(en?'Permissions could not be saved.':'Yetkiler kaydedilemedi.');}finally{setBusy(false);}};
 const can=key=>data&&clanAllowed(data.role,data.permissions,key),server=!!act?.isServer?.();
 return <section className="clan-management"><header><h3>{en?'Clan headquarters':'Klan merkezi'}</h3><span>{en?'Shared storage & roles':'Ortak depo ve yetkiler'}</span></header><div className="clan-mgmt-tabs">{[['vault','Depo','Storage'],['log','Hareketler','Activity'],['roles','Yetkiler','Permissions']].map(([key,tr,eng])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{en?eng:tr}</button>)}</div>{error&&<p role="alert" className="clan-error">{error}</p>}{!data?<button onClick={load}>{en?'Load storage':'Depoyu yükle'}</button>:<>
 {tab==='vault'&&<>{!server&&<p>{en?'Shared items require server-authoritative economy on this account.':'Ortak eşya aktarımı için hesabın sunucu ekonomisi açık olmalı.'}</p>}<div className="clan-vault-heading"><b>{en?'Clan storage':'Klan deposu'} · {data.items.length}/{data.capacity}</b><button disabled={busy} onClick={load}>{en?'Refresh':'Yenile'}</button></div><div className="clan-vault-grid">{data.items.map(({id,item})=><button disabled={busy||!server||!can('withdraw')} key={id} onClick={()=>run('clan/vaultWithdraw',{vaultId:id})}><ItemIcon item={item} size={46}/><span>{displayItemName(item)}</span><small>{en?'Take':'Al'}</small></button>)}</div>{!data.items.length&&<p>{en?'Storage is empty.':'Depo henüz boş.'}</p>}<h4>{en?'Deposit from your bag':'Çantandan depoya koy'}</h4><div className="clan-vault-grid">{player.inventory.filter(i=>['weapon','armor','accessory','clanMaterial'].includes(i.kind)).map(item=><button key={item.id} disabled={busy||!server||!can('deposit')} onClick={()=>run('clan/vaultDeposit',{itemId:item.id})}><ItemIcon item={item} size={44}/><span>{displayItemName(item)}</span><small>{en?'Deposit':'Koy'}</small></button>)}</div></>}
 {tab==='roles'&&<><p>{en?'The leader always retains full access. Role changes apply to every character with that role.':'Lider tüm yetkileri korur. İzinler o role sahip tüm karakterlere uygulanır.'}</p><div className="clan-role-table"><div/><b>{en?'Deputy':'Yrd.'}</b><b>{en?'Officer':'Memur'}</b><b>{en?'Member':'Üye'}</b>{CLAN_PERMISSIONS.map(key=><div className="clan-role-row" key={key}><span>{LABELS[key][en?1:0]}</span>{['deputy','officer','member'].map(role=><input type="checkbox" key={role} aria-label={`${LABELS[key][en?1:0]} · ${role}`} checked={draft[role][key]} disabled={busy||data.role!=='leader'} onChange={e=>setDraft(d=>({...d,[role]:{...d[role],[key]:e.target.checked}}))}/>)}</div>)}</div>{data.role==='leader'&&<button className="clan-save" disabled={busy} onClick={save}>{en?'Save permissions':'Yetkileri kaydet'}</button>}</>}
 {tab==='log'&&<div className="clan-vault-log">{!data.log.length&&<p>{en?'No transfers yet.':'Henüz aktarım yok.'}</p>}{data.log.map(row=><article key={row.id}><b>{player.clan.members.find(m=>m.accountId===row.account_id&&m.characterKey===row.character_key)?.name||row.account_name}</b><span>{row.action==='deposit'?(en?'Deposited':'Depoya koydu'):(en?'Withdrew':'Depodan aldı')} · {row.item_name}</span><time>{new Date(row.created_at).toLocaleString(en?'en-GB':'tr-TR')}</time></article>)}</div>}
 </>}</section>;
}
