import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import CharacterFigure from '../components/CharacterFigure';
import {BALANCED_WEAPONS} from '../data/balancedWeapons';
import {initialPlayer,equipItem} from '../utils/player';
import {gmBuildWeaponById,gmWeaponTemplates} from '../utils/loot';
import arena from '../assets/battle/arena-v1.png';
function fresh(cls,race){return {...initialPlayer(cls,race,'Önizleme'),level:65,stats:{str:300,dex:300,int:300,mag:300,sta:300}};}
function Demo(){const [p,setP]=useState(()=>fresh('warrior','human')),[plus,setPlus]=useState(1),[message,setMessage]=useState('');
 function equip(name){if(!name){setP({...p,equipped:{...p.equipped,mainHand:null},inventory:p.equipped.mainHand?[...p.inventory,p.equipped.mainHand]:p.inventory});return;}const template=gmWeaponTemplates(p.class).find(w=>w.name===name),item=gmBuildWeaponById(p.class,template.id,plus),r=equipItem({...p,inventory:[...p.inventory,item]},item);setMessage(r.blocked||'Kuşanıldı');setP(r.player);}
 return <main><h1>Karakter & silah</h1><p>Bu deneme oyun kaydını değiştirmez.</p><nav><select aria-label="Sınıf" value={p.class} onChange={e=>setP(fresh(e.target.value,p.race))}>{['warrior','rogue','mage'].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Irk" value={p.race} onChange={e=>setP({...p,race:e.target.value})}><option value="human">Human</option><option value="karus">Karus</option></select><select aria-label="Upgrade" value={plus} onChange={e=>{setPlus(+e.target.value);if(p.equipped.mainHand)setP({...p,equipped:{...p.equipped,mainHand:{...p.equipped.mainHand,upgradeLevel:+e.target.value}}});}}>{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></nav><select className="weapon" aria-label="Silah" value={p.equipped.mainHand?.name||''} onChange={e=>equip(e.target.value)}><option value="">Silahsız</option>{!BALANCED_WEAPONS[p.class].some(w=>w.name===p.equipped.mainHand?.name)&&p.equipped.mainHand&&<option disabled>{p.equipped.mainHand.name}</option>}{BALANCED_WEAPONS[p.class].map(w=><option key={w.name}>{w.name}</option>)}</select><div className="views"><section className="battle" style={{backgroundImage:`url(${arena})`}}><h2>Savaş görünümü</h2><CharacterFigure player={p}/></section><section className="inventory paperdoll-character"><h2>Kuşanılmış</h2><CharacterFigure player={p}/></section></div><p role="status">{message} · {p.equipped.mainHand?.name||'Silahsız'}</p></main>;
}
document.head.insertAdjacentHTML('beforeend','<style>body{margin:0;background:#101719;color:#efdfc4;font:14px system-ui}main{max-width:850px;margin:auto;padding:18px}h1{font-size:24px}h2{font-size:14px;text-align:center}nav{display:flex;gap:10px}select{padding:12px;background:#273137;color:#eee;border:1px solid #78715e;border-radius:8px}.weapon{width:100%;margin:12px 0}.views{display:grid;grid-template-columns:2fr 1fr;gap:20px}.views section{height:430px;border:1px solid #916d40;border-radius:12px;overflow:hidden}.battle{background-size:cover;background-position:center}.inventory{background:linear-gradient(#b97a342f,#1d232a)}.views .character-figure{height:365px}@media(max-width:600px){.views{gap:8px;grid-template-columns:3fr 2fr}.views section{height:300px}.views .character-figure{height:250px}}</style>');
createRoot(document.querySelector('#root')).render(<Demo/>);


